server {
    listen 80;
    server_name satscap.com;
    return 301 https://www.satscap.com$request_uri;
}

server {
    listen 80;
    server_name www.satscap.com _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
